CREATE TABLE IF NOT EXISTS api_config
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    application_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    base_url character varying COLLATE pg_catalog."default" NOT NULL,
    token character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT api_config_pkey PRIMARY KEY (id, application_name),
    CONSTRAINT api_config_appname UNIQUE (application_name)
)