export const appConstants = {
    STRAPI_APPLICATION_NAME: "STRAPI",
    ERR_MANDATORY: "mandatory",
    ERR_INVALID_URL: "invalidConfigUrl",
    ERR_MALFORMED_URL: "malformedConfigUrl",
    ERR_INVALID_TOKEN: "invalidToken",
    ERR_TOKEN_PERMISSIONS: "invalidTokenPermissions",
    ERR_MALFORMED_TOKEN: "malformedToken",
    STRAPI_CONFIG_ENDPOINT: "/api/strapi/config",
    STRAPI_CONTENT_TYPES_ENDPOINT: "/content-type-builder/content-types",
    STRAPI_COMPONENTS_ENDPOINT: "/content-type-builder/components",
    GOT_ERR_NON_2XX_3XX_RESPONSE: "ERR_NON_2XX_3XX_RESPONSE",
    HTTP_CODE_FORBIDDEN: "403",
    HTTP_CODE_UNAUTHORIZED: "401",
    MSG_TOKEN_HAS_SPACES: "Token has spaces",
    MSG_TOKEN_VERIFY_SUCCESS: "Strapi config verified succesfully",
    MSG_STRAPI_BAD_PAYLOAD: "Bad endpoint data payload",
    TOKEN_FIELD_NAME: "token",
    CONFIGURL_FIELD_NAME: "configUrl",
    AUTH_HEADER: "Authorization",
    BEARER: "Bearer ",
    PEM_HEADER: "-----BEGIN CERTIFICATE-----\n",
    PEM_FOOTER: "\n-----END CERTIFICATE-----"
}